### ISSUE TITLE
Is this still being maintained?

### ISSUE THREAD

**Issue by debrisapron** [latentflip/domthing#19]
I attempted to use this a while ago, but quickly hit a raft of problems and bugs. I notice the repo has not been touched in six months (as of writing). I find this frustrating because I would very much like to use domthing for my ampersand app - I find the plain-html-plus-bindings style tiresomely verbose, but using interpolation libraries like handlebars requires re-rendering views on every change.

I feel strongly that if this is abandonware it should be removed from the official ampersand docs & examples rather than leading developers down a blind alley.

**Comment by latentflip** [comment]
Yes, you're right, it's not being maintained, as I've been using react in place of this myself. If someone wants to pick it up and developer it, they're welcome, but I shall remove it from the docs.

**Comment by latentflip** [comment]
I think I've found all references to domthing.

**Comment by latentflip** [comment]
Hope that's satisfactory @debrisapron?

**Comment by debrisapron** [comment]
Sad, but thanks for update.
